Ruby on Rails/Lab3/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "books#index"
  resources :books
  resources :users
end

Ruby on Rails/Lab3/app/models/book.rb
class Book < ApplicationRecord
  validates :name, presence: true, length: {minimum:3}
  validates :price, presence: true
  validates :image,presence: true
  validates :description,presence: true
  has_one_attached :image
  belongs_to :user
end

Ruby on Rails/Lab3/app/models/user.rb
class User < ApplicationRecord
  has_many :books
end

Ruby on Rails/Lab3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Ruby on Rails/Lab3/app/controllers/books_controller.rb
class BooksController < ApplicationController

  http_basic_authenticate_with name: "Hager", password: "Hager1234", except: [:index, :show]

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = User.find_by(name: authenticated_username).id

    if @book.save
      @book.image.attach(params[:book][:image])
      redirect_to @book
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      if params[:book][:image].present?
        @book.image.attach(params[:book][:image])
      end
      redirect_to @book
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def book_params
      params.require(:book).permit(:name, :price, :description, :image)
    end

  private
    def authenticated_username
      username, _password = ActionController::HttpAuthentication::Basic::user_name_and_password(request)
      username
    end

end

Ruby on Rails/Lab3/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

Ruby on Rails/Lab3/app/helpers/books_helper.rb
module BooksHelper
end

Ruby on Rails/Lab3/app/helpers/users_helper.rb
module UsersHelper
end

Ruby on Rails/Lab3/app/views/books/_form.html.erb
<style>
  .form{
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      font-family: 'calibri';
      width: 100%;
      height: 80vh;
  }

  .form-container{
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    border: 1px solid #ddd;
    padding: 40px;
    border-radius: 5px;
  }

  label{
    font-weight: bold;
  }

  input{
    height: 3.5vh;
    width: 100%;
    border: solid thin #ddd;
  }

  textarea{
    height: 5vh;
    width: 100%;
    border: solid thin #ddd;
  }

  .form-field {
    margin-bottom: 20px;
    width: 200px;
  }

  .error-message {
    color: red;
    margin-top: 5px;
  }

  .form-actions {
    margin-top: 10px;
  }

  button{
    padding: 0.2%;
    width: 8%;
    border: solid thin #ddd;
  }

  a{
    text-decoration: none;
    color: #000;
  }
</style>

<div class="form">
  <%= form_with model: book do |form| %>
  <div class="form-container">
    <div class="form-field">
      <%= form.label :name %>
      <%= form.text_field :name %>
      <% book.errors.full_messages_for(:name).each do |message| %>
        <div class="error-message"> <%= message %> </div>
      <% end %>
    </div>

    <div class="form-field">
      <%= form.label :description %>
      <%= form.text_area :description %>
      <% book.errors.full_messages_for(:description).each do |message| %>
        <div class="error-message"> <%= message %> </div>
      <% end %>
    </div>

    <div class="form-field">
      <%= form.label :price %>
      <%= form.text_field :price %>
      <% book.errors.full_messages_for(:price).each do |message| %>
        <div class="error-message"> <%= message %> </div>
      <% end %>
    </div>

    <div class="form-field">
      <%= form.label  :image %>
      <%= form.file_field :image %>
      <% book.errors.full_messages_for(:image).each do |message| %>
        <div class="error-message"> <%= message %> </div>
      <% end %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  </div>
  <% end %>

  <button class="form-actions">
    <%= link_to 'Back', books_path %>
  </button>
</div>

Ruby on Rails/Lab3/app/views/books/edit.html.erb
<style>
    h1{
        font-family: "calibri";
        text-align: center;
    }
</style>

<h1>UPDATE BOOK</h1>

<%= render "form", book: @book %>

Ruby on Rails/Lab3/app/views/books/index.html.erb
<style>
    *{
        font-family: "calibri";
    }

    h1{
        text-align: center;
    }

    table {
        width: 75%;
        margin-left: 12.5%;
        border-collapse: collapse;
        border: solid thin #ddd;
    }

    th, td {
        padding: 8px;
        font-size: 16.5px;
        text-align: center;
        border-bottom: 1px solid #ddd;
    }

    th {
        background-color: #f2f2f2;
        font-weight: bold;
    }

    a {
        color: #000;
        text-decoration: none;
    }

    button{
        border: solid thin #ddd;
    }

    .add-btn{
        width: 10%;
        padding: 0.5%;
        margin-left: 45%;
        margin-top: 2%;
    }
</style>

<h1>BOOK STORE</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th>Created by</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.id %></td>
        <td><%= book.name %></td>
        <td><%= book.price %></td>
        <td><%= book.description %></td>
        <td><%= link_to book.user.name, user_path(book.user) %></td>
        <td><%= book.created_at %></td>
        <td><%= book.updated_at %></td>
        <td>
            <button><%= link_to "View", book %></button>
            <button><%= link_to "Edit", edit_book_path(book) %></button>
            <button>
                <%= link_to "Delete", book_path(book), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure you want to delete this book?"
                } %>
            </button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<button class="add-btn"><%= link_to "Add New Book", new_book_path %></button>

Ruby on Rails/Lab3/app/views/books/new.html.erb
<style>
    h1{
        font-family: "calibri";
        text-align: center;
    }
</style>

<h1>ADD NEW BOOK</h1>

<%= render "form", book: @book %>

Ruby on Rails/Lab3/app/views/books/show.html.erb
<style>
    .book {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 95vh;
        font-family: 'calibri'
    }

    .book-details {
        width: 60%;
        display: flex;
        align-items: center;
        justify-content: space-between;
        border: solid thin #ddd;
        margin-bottom: 2%;
    }

    img {
        width: 500px;
        height: 500px;
    }

    .book-info{
        padding-right: 8%;
    }

    .book-info p {
        margin-bottom: 10px;
    }

    button{
        padding: 0.2%;
        width: 8%;
        border: solid thin #ddd;
    }

    a{
        text-decoration: none;
        color: #000;
    }
</style>


<div class="book">
    <div class="book-details">
        <div class="book-image">
            <%= image_tag(@book.image, alt: "Book Image") %>
        </div>
        <div class="book-info">
            <h1><%= @book.name %></h1>
            <p><strong>Price:</strong> $<%= @book.price %></p>
            <p><strong>Description:</strong> <%= @book.description %></p>
            <p><strong>Created At:</strong> <%= @book.created_at %></p>
            <p><strong>Updated At:</strong> <%= @book.updated_at %></p>
        </div>
    </div>
    <button>
    <%= link_to 'Back', books_path %>
</button>
</div>

Ruby on Rails/Lab3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Ruby on Rails/Lab3/app/views/users/show.html.erb
<style>
  .user-details {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    height: 97vh;
    font-family: Arial, sans-serif;
  }

  .user-details h1 {
    font-size: 24px;
    font-weight: bold;
    margin-bottom: 10px;
  }

  .user-details p {
    margin: 5px 0;
    border: solid thin #ddd;
    padding: 0 5%;
  }

  .user-details strong {
    font-weight: bold;
  }

  button{
    padding: 0.2%;
    margin-top: 3%;
    width: 8%;
    border: solid thin #ddd;
  }

  a{
    text-decoration: none;
    color: #000;
  }
</style>

<div class="user-details">
  <h1>User Details</h1>
  <p><strong>Name:</strong> <%= @user.name %></p>
  <p><strong>Email:</strong> <%= @user.email %></p>
  <button class="form-actions">
    <%= link_to 'Back', books_path %>
  </button>
</div>